#!/usr/bin/with-contenv sh

chown -R postgres.postgres $PGDATA
chmod 700 $PGDATA

if [ ! -f $PGDATA/PG_VERSION ];then
    s6-setuidgid postgres initdb
    cp /configs/postgresql.conf $PGDATA/.
    cp /configs/pg_hba.conf $PGDATA/.
    chown -R postgres.postgres $PGDATA
fi

mkdir -p /run/postgresql
chown -R postgres.postgres /run/postgresql
